repos:
  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        args: [--style, google, -i, --parallel]
        files: '\.py$'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/python/mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--python-version=3.12, bitcoin/]
        pass_filenames: false
        additional_dependencies: [typer]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.7.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-case-conflict
