"""Re-exports all Bitcoin script types, classifiers, builders, and opcodes.

Aggregates the public API from the submodules: parser, classifier, builder,
and opcodes.
"""

from bitcoin.script.builder import (
    build_p2pk,
    build_p2pkh,
    build_p2sh,
    build_p2tr,
    build_p2wpkh,
    build_p2wsh,
    make_p2pkh_script,
)
from bitcoin.script.classifier import (
    MULTISIG,
    NON_STANDARD,
    P2PK,
    P2PKH,
    P2SH,
    P2TR,
    P2WPKH,
    P2WSH,
    TIMELOCK,
    classify_detailed,
    classify_script_pubkey,
    classify_script_sig,
    has_timelocks,
    is_bare_multisig,
    is_op_return,
)
from bitcoin.script.opcodes import (
    OP_0,
    OP_1,
    OP_1NEGATE,
    OP_16,
    OP_CHECKLOCKTIMEVERIFY,
    OP_CHECKMULTISIG,
    OP_CHECKSEQUENCEVERIFY,
    OP_CHECKSIG,
    OP_DUP,
    OP_EQUAL,
    OP_EQUALVERIFY,
    OP_HASH160,
    OP_PUSHDATA1,
    OP_PUSHDATA2,
    OP_PUSHDATA4,
    OP_RETURN,
    OPCODES_BY_NAME,
    OPCODES_BY_VALUE,
)
from bitcoin.script.parser import (
    Opcode,
    Push,
    ScriptChunk,
    ScriptElement,
    parse_multisig_redeem_script,
    reject_code_separators,
    script_to_string,
    serialize_script,
)
from bitcoin.script.parser import (
    parse_script_chunks as parse_script,)
from bitcoin.script.taproot import (
    TaprootScriptPath,
    get_x_only_pubkey,
    parse_taproot_witness_stack,
)

__all__ = [
    "MULTISIG",
    "NON_STANDARD",
    "OP_0",
    "OP_1",
    "OP_16",
    "OP_1NEGATE",
    "OP_CHECKSIG",
    "OP_CHECKLOCKTIMEVERIFY",
    "OP_CHECKMULTISIG",
    "OP_CHECKSEQUENCEVERIFY",
    "OP_DUP",
    "OP_EQUAL",
    "OP_EQUALVERIFY",
    "OP_HASH160",
    "OP_PUSHDATA1",
    "OP_PUSHDATA2",
    "OP_PUSHDATA4",
    "OP_RETURN",
    "OPCODES_BY_NAME",
    "OPCODES_BY_VALUE",
    "Opcode",
    "P2PK",
    "P2PKH",
    "P2SH",
    "P2TR",
    "P2WPKH",
    "P2WSH",
    "Push",
    "ScriptChunk",
    "ScriptElement",
    "TaprootScriptPath",
    "get_x_only_pubkey",
    "parse_taproot_witness_stack",
    "TIMELOCK",
    "build_p2pk",
    "build_p2pkh",
    "build_p2sh",
    "build_p2tr",
    "build_p2wpkh",
    "build_p2wsh",
    "classify_detailed",
    "classify_script_pubkey",
    "classify_script_sig",
    "has_timelocks",
    "is_bare_multisig",
    "is_op_return",
    "make_p2pkh_script",
    "parse_multisig_redeem_script",
    "parse_script",
    "reject_code_separators",
    "script_to_string",
    "serialize_script",
]
